<?php
/**
 * @file Implements features regarding sales reports.
 *
 */

/**
 * Implements hook_menu()
 */
function api_sales_report_menu() {
  $items['admin/config/api/sales-report'] = array(
    'title' => 'Sales Report',
    'access callback' => 'api_sales_report_access',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('api_sales_report_page', 5, 6, 7, 8, 9, 10, 11, 12),
    'file' => 'api_sales_report.pages.inc',
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

/**
 * Implements hook_theme().
 */
function api_sales_report_theme($existing, $type, $theme, $path) {
  return array(
    'api_sales_report_summary_report' => array(
      'template'  => 'api-sales-report-summary-report',
      'path' => $path . '/templates',
      'variables' => array(
        'safety_key_stats' => NULL,
        'user_stats' => NULL,
        'company_stats' => NULL,
      ),
    ),
  );
}

/**
 * Implements Sales Report Access Callback.
 */
function api_sales_report_access() {
  global $user;
  $roles = array_intersect(array('administrator', 'customer support'), $user->roles);
  if (!empty($roles)) {
    return TRUE;
  }
  return FALSE;
}
