<?php

/**
 * Custom change password form
 */
function user_password_change_form_alter(&$form, $form_state, $form_id) {
    global $user;
    $form_errors = form_set_error();
    if (!empty($form_errors['pass'])
            && strpos($form_errors['pass'], t('Your password has not met the following requirement')) == 0
            && $user->uid != 0) {
        form_clear_error();
        unset ($_SESSION['messages']['error']);
        form_set_error('pass', t('Invalid new password, please check length and complexity.'));
    }
    if (!empty($form_errors['current_pass'])) {
        form_clear_error();
        unset ($_SESSION['messages']['error']);
        form_set_error('current_pass', t('Invalid current password, please try again.'));
    }

    if ($form_id == 'user_profile_form') {
        $account = $form['#user'];
        $admin = user_access('administer users');
        $form['account']['current_pass']['#description'] = '';
        $form['account']['current_pass']['#weight'] = 0;
        $form['account']['pass']['#description'] = '';
        $form['account']['mail']['#weight'] = -1;
        $form['account']['name'] = array(
            '#type' => 'textfield',
            '#title' => t('Username'),
            '#value' => $account->name,
            '#disabled' => $admin ? FALSE:TRUE,
            '#size' => 25,
            '#weight' => 0,
        );

        if ($admin){
            hide($form['actions']['cancel']);
        } else {
            $form['#attached']['js'][drupal_get_path('module', 'user_password_change') . '/js/user_password_change.js'] = array('type' => 'file');
            $form['account']['fake_pass'] = $form['account']['current_pass'];
            $form['account']['fake_pass']['#disabled'] = true;
            $form['account']['fake_pass']['#title'] = t('Password');
            $form['account']['link_change_pass'] = array(
                '#type' => 'link',
                '#title' => t('Change Password'),
                '#id' => 'change-pass',
                '#weight' => 1,
            );
            $form['account']['show_character_pass'] = array(
                '#type' => 'checkbox',
                '#title' => t('Show characters '),
                '#id' => 'show-character-pass',
                '#weight' => 1,
            );
            $form['actions']['cancel'] = array(
                '#markup' => '<div class="back-to-login clearfix">'. l(t('Cancel'),'user/'.$account->uid,
                         array('attributes' => array('class' => 'login-account'))). '</div>',
            );
        }
    }

    // Change submit button label from reset password form
    if ($form_id == 'user_pass') {
      $form["actions"]["submit"]["#value"] = t('Request Password Reset');
    }
}
